### ISSUE TITLE
Support remote debgging

### ISSUE THREAD

**Issue by kirantambe** [gotcha/ipdb#102]
When there is no access to stdin and stdout of a machine this can be useful. Eg. Debugging issues on a server from a remote machine.

**Comment by gotcha** [comment]
PR welcome ;-)

**Comment by kasisnu** [comment]
@gotcha Could you leave some pointers for how to make this work? We have a requirement for this and I'm happy to work on it.

If we don't think this is in scope for ipdb, then maybe a separate project is needed?

**Comment by fx-kirin** [comment]
FYI, it's worth to try these two.

https://github.com/tamentis/rpdb

https://github.com/romanvm/python-web-pdb

**Comment by arusahni** [comment]
There's also: https://github.com/ionelmc/python-remote-pdb
