### ISSUE TITLE
ipdb list command overrides list() type conversion

### ISSUE THREAD

**Issue by lucidv01d** [gotcha/ipdb#106]
Since the word _list_ is used both as a ipdb command and a way to cast lists, it's very difficult to do the latter when debugging with ipdb. Is there a workaround?

**code instrumented with ipdb.set_trace:**

```
import ipdb
ipdb.set_trace()

ipdb> list(('anything', 'at all'))
*** Error in argument: "(('anything', 'at all'))"
```

**ipython:**

```
In [1]: list(('anything', 'at all'))
Out[1]: ['anything', 'at all']
```

**Comment by gotcha** [comment]
I do not have a quick idea. You might want to ask to IPython community.

**Comment by parejkoj** [comment]
I addition to the upvote above, I'll add a comment: I ran into this via `list(dict.values())`, same as #92, which is linked from here. This is going to be a bigger problem as more people move into python3 and have to do list conversions of dict keys/values.

You can work around this by using `p list((1,2,3))`, to force a "print". I'm not sure what a better idea would be, but this certainly confused me.

**Comment by gnebehay** [comment]
The solution to all of these problems is to use
```
ipdb> !list(('anything', 'at all'))
['anything', 'at all']
```
The `!` basically circumvents all internal debugger commands.
