### ISSUE TITLE
Variable value change doesn't happen

### ISSUE THREAD

**Issue by sagargrover** [gotcha/ipdb#107]
Suppose there is a piece of code like
```
import ipdb; ipdb.set_trace();
m = ((a is True) and (b is True))           //Suppose gives m = False
if m is True:
   do something
```
Now if you run this and press _n_ in ipdb console, it will set _m_ value to True.
Now on the ipdb shell if you try to set value of _m_ to True, it just doesn't happen. It always remains False. 
I am assuming ipdb doesn't allow variables value set before ipdb statement not to change. Is that a bug or is it something ipdb has mandated?

**Comment by vladiibine** [comment]
Extra context: this seems to happen for ipython 5, but not ipython 4.

**Comment by vladiibine** [comment]
More context, I think it's a bug in ipython 5, since it works like this even with no ipdb installed (tested it with the ipython `%debug` command)

**Comment by vladiibine** [comment]
Created this issue for IPython 5:
https://github.com/ipython/ipython/issues/9887

**Comment by gotcha** [comment]
Thanks for having tracked the issue until you could attribute it to IPython

**Comment by vladiibine** [comment]
I could, but there's a lot more tracking to be done until that point :dancer: 
I guess you can close the issue now.

**Comment by gotcha** [comment]
I think that you misunderstood what I meant: 
I am thanking you because you have found that the bug comes from IPython.
I am not asking to do more.

**Comment by vladiibine** [comment]
oh, my bad, I misread "attribute", thought you said "contribute" :) Thanks for the cool lib man!
