### ISSUE TITLE
Is this project still under active development?

### ISSUE THREAD

**Issue by mbc1990** [gotcha/ipdb#122]
ipdb is a great tool and I use it every day, but the last PR merged was on Jun 14, 2016. There are currently four (well really three because two of them fix the same bug) open PRs that need attention.

**Comment by gnebehay** [comment]
I tend to believe that this project is obsolete, as all of the functionality moved to IPython. [http://ipython.readthedocs.io/en/stable/api/generated/IPython.terminal.debugger.html](http://ipython.readthedocs.io/en/stable/api/generated/IPython.terminal.debugger.html)

**Comment by alichaudry** [comment]
@gnebehay I wasn't able to find the `run_call` method in IPython's debugger. Do you know if that's been obsoleted? I used to be able to call it as follows:

```python
import ipdb
ipdb.runcall(func, *args, **kwargs)
```

**Comment by gnebehay** [comment]
The IPython terminal debugger is a subclass of the standard pdb debugger
and therefore has a runcall method, as described here:
https://docs.python.org/2/library/pdb.html#pdb.runcall

**Comment by gnebehay** [comment]
I am now a contributor to this repository and will try to get things going more quickly.
