### ISSUE TITLE
ipdb version

### ISSUE THREAD

**Issue by BjornFJohansson** [gotcha/ipdb#139]
Hi, and thanks for a really useful piece of software. I wonder if there is a way for 
ipdb to report its own version, like a __version__ variable in __init__.py?
If there isn't one, maybe there should be?

**Comment by gotcha** [comment]
There could definitely be one. PR welcome !

**Comment by BjornFJohansson** [comment]
I use [versioneer](https://github.com/warner/python-versioneer) because it connects well to git (git tags become version numbers). This works really well and I use it for all my own projects.

However, this means that the main developer has to implement a workflow that fits this (gitflow).
Otherwise, its just to add a __version__ string. 

I can do a PR for any of them, which one do you prefer?

**Comment by gotcha** [comment]
I prefer the __version__ (I am lazy to learn versioneer ;-)

**Comment by BjornFJohansson** [comment]
ok!
