### ISSUE TITLE
Provide a configuration mechanism to set context by default without explicitly passing context= argument every time

### ISSUE THREAD

**Issue by cirosantilli** [gotcha/ipdb#147]
To increase the context, I currently do:

```
ipdb.set_trace(context=21)
```

Is it possible to have a configuration mechanism on some rc file, that allows me to type just:

```
ipdb.set_trace()
```

and still get the larger context?

Or even better, just increase the default context :-) 99% of users likely want that.

https://stackoverflow.com/questions/6240887/how-can-i-make-ipdb-show-more-lines-of-context-while-debugging/6449663

**Comment by cirosantilli** [comment]
OMG amazing.

**Comment by ernop** [comment]
Curious why the default is 1 line before/after.  It seems much more convenient to have 5 or 10 so you can see where you are. Terminals can support it.
