### ISSUE TITLE
Install latest on Ubuntu 14

### ISSUE THREAD

**Issue by curioussavage** [gotcha/ipdb#148]
The version installed in apt is old on this version and I have this issue https://github.com/gotcha/ipdb/issues/52.

Looking for a simple way to install the latest version but I couldn't find any PPAs. Just thought I would ask here if anyone maintains one.

**Comment by zabulazza** [comment]
@curioussavage I would not recommend install it via apt since apt packages might be obsolete.
The best way I see is install it using pip - in this case latest version from pypi will be installed.

**Comment by gotcha** [comment]
@zabulazza Right, I do not maintain apt packages.
