### ISSUE TITLE
ipdb shows modified file instead of file from memory

### ISSUE THREAD

**Issue by alphaCTzo7G** [gotcha/ipdb#149]
I typically run a file through `ipdb` and sometimes while running it through the debbuger, I figure out the bugs and incorporate it into the code.

Once that is done, I would still expect that ipdb would show the file in memory, rather the file on disk(if it is modified). However, it shows the modified file but actually runs the file already loaded into memory.

Is this something that can be fixed?

**Comment by gotcha** [comment]
I do not think it can be fixed. AFAIK, the python interpreter uses an intermediary bytecode format that is actually run. I think that code contains pointers (filename and line numbers) to the code it was compiled from.
If the python file changes, those hints do not correspond anymore.
