### ISSUE TITLE
Why can't we use double semicolon together(;;) in a string in python? How do we achieve this?

### ISSUE THREAD

**Issue by nOOBIE-nOOBIE** [gotcha/ipdb#172]
I am trying to have a string with two semicolons together while debugging.

Example
```
my_string = ";;AjaxControlToolkit, Version=4.1.50508"
```
python returns

```
SyntaxError: EOL while scanning string literal
```
My guess is that one of the semicolons is escaping the quote. because when I escape the second quote and replace the backslash it works. I don't get any errors.
```
my_string = ';/;AjaxControlToolkit, Version=4.1.50508'.replace('\\','')
my_string
```
```
';;AjaxControlToolkit, Version=4.1.50508'
```
The case is the same if I try to use more than two semicolons together.

However, I can also achieve the result I want by concatenating two semicolons.

Example
```
my_string = ";"+";AjaxControlToolkit, Version=4.1.50508"
print(my_string)
```

```
';;AjaxControlToolkit, Version=4.1.50508'
```
Why does this happen?

**Comment by gotcha** [comment]
I have tried that way of initializing a string in Python 2.7, Python 3.7, IPython 7.8 under 3.7.

None of them make an issue.

What is your context ?

**Comment by nOOBIE-nOOBIE** [comment]
I am sorry for the lack of information. 
Here is how i got into error.

```
#script.py
import ipdb
ipdb.set_trace()
```

If we run this with 
```
python3 script.py
```

we end up in debug terminal correct?

so in debug terminal. it appears that i cannot make a string with two semicolons together in it.

for example
```
";;AjaxControlToolkit, Version=4.1.50508"
```
throws a error.

**Comment by gotcha** [comment]
I could reproduce. And also if I replace with `pdb` instead of `ipdb`.

The "bug" is actually documented in https://docs.python.org/3/library/pdb.html (Search for ;;)

**Comment by gotcha** [comment]
FYI, you could express your string as:`';'';'`.

In Python `'a''b'` is equivalent to `'ab'`. Or `"a""b"`, or `'a'"b"`

**Comment by nOOBIE-nOOBIE** [comment]
> I could reproduce. And also if I replace with `pdb` instead of `ipdb`.
> 
> The "bug" is actually documented in https://docs.python.org/3/library/pdb.html (Search for ;;)

Makes total sense to me now why the error happened earlier. The `;;` is supposed to be a seperator. So the `EOL` error occured

> Multiple commands may be entered on a single line, separated by ;;. (A single ; is not used as it is the separator for multiple commands in a line that is passed to the Python parser.) No intelligence is applied to separating the commands; the input is split at the first ;; pair, even if it is in the middle of a quoted string.

![image](https://user-images.githubusercontent.com/24412619/67942261-9534ab80-fbff-11e9-8060-f0a0b9793a24.png)


Thanks
