### ISSUE TITLE
await does not work in ipdb, even though IPython supports it

### ISSUE THREAD

**Issue by darthdeus** [gotcha/ipdb#174]
IPython REPL does support `await`, but ipdb doesn't.

```python
Python 3.8.0 (default, Oct 23 2019, 18:51:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import asyncio

In [2]: await asyncio.sleep(1)

In [3]: import ipdb; ipdb.set_trace()
--Call--
> /usr/lib/python3.8/site-packages/IPython/core/displayhook.py(252)__call__()
    251
--> 252     def __call__(self, result=None):
    253         """Printing with history cache management.

ipdb> await asyncio.sleep(1)
*** SyntaxError: 'await' outside function
```

Tested with ipdb 0.12.2

**Comment by gotcha** [comment]
@darthdeus Can you check if `pdb` supports it ?

**Comment by darthdeus** [comment]
It does not, so I guess this is an issue on their end, right?

```python
>>> import pdb
>>> pdb.set_trace()
--Return--
> <console>(1)<module>()->None
(Pdb) await asyncio.sleep(1)
*** SyntaxError: 'await' outside function
```

Might be worth noting that for regular Python it only seems to work in the asyncio REPL, so

```python
$ python
Python 3.8.0 (default, Oct 23 2019, 18:51:26)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> await asyncio.sleep(1)
  File "<stdin>", line 1
SyntaxError: 'await' outside function
>>>
$ python -m asyncio
asyncio REPL 3.8.0 (default, Oct 23 2019, 18:51:26)
[GCC 9.2.0] on linux
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> await asyncio.sleep(1)
>>>
```

Seems to be because of https://bugs.python.org/issue37028 (commit https://github.com/python/cpython/commit/16cefb0bc7b05c08caf08525398ff178c35dece4). Any idea how to use this explicitly in pdb/ipdb?

**Comment by gotcha** [comment]
@darthdeus

I do not know enough of `async` `await` to really help here... but I have the gut feeling that it will never be possible to run `await` from `pdb`.

You should ask in the Python community.

Closing for now, do not hesitate to reopen if `ipdb` could do something to support it.

**Comment by mindojo-victor** [comment]
https://bugs.python.org/issue37028

**Comment by pirate** [comment]
What is the solution to debug async functions in a REPL these days? Is it still impossible in ipdb?

**Comment by weird-ai-art** [comment]
@pirate there is `await pdb.set_trace_async()`
