### ISSUE TITLE
What makes django tests stop when ipdb is found?

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [gotcha/ipdb#186]
Hello, I'm currently working with [green](https://github.com/CleanCut/green) (a test runner) and I'd like to know more about how django stops whenever there's an ipdb breakpoint. Currently green doesn't support pdb breakpoints (just ignores it completely), and I'm trying to understand how I can make it stop on breakpoints.

Any help is greatly appreciated!

**Comment by gotcha** [comment]
I think you have more chances to get your question answered by asking it to the Django community.
