### ISSUE TITLE
ipdb won't quit

### ISSUE THREAD

**Issue by 3rock618** [gotcha/ipdb#188]
When running a `post_mortem()` inside a loop, quit does not exit the loop

``` python
import ipdb
while True:
    try    : 1/0 
    except : ipdb.post_mortem()
```

``` python
In [1]: import ipdb 
   ...: while True: 
   ...:     try    : 1/0 
   ...:     except : ipdb.post_mortem() 
   ...:   

> <ipython-input-1-fd67498556c7>(3)<module>()
      2 while True:
----> 3     try    :1/0
      4     except :ipdb.post_mortem()

ipdb> q

> <ipython-input-1-fd67498556c7>(3)<module>()
      2 while True:
----> 3     try    :1/0
      4     except :ipdb.post_mortem()

ipdb>
```

The whole reason I'm using this pattern is because, based on what I discover in debugging, I want `continue` to restart into the loop (which it does) and `quit` to break the loop. (Imagine `1/0` is actually some `usefulfunction()`)

**Comment by gotcha** [comment]
I personally never use `post_mortem`. Did you check that what you try does work with standard `pdb` ?

**Comment by 3rock618** [comment]
You're correct to point out that pdb has the same behavior. closed.
