### ISSUE TITLE
Difficult to debug a variabled named "r"

### ISSUE THREAD

**Issue by mankoff** [gotcha/ipdb#207]
I have a variable named `r`, and I cannot easily debug it with `ipdb` because of the `r` command. Example:

```python
import ipdb

def foo():
    r = 42
    x = 42
    ipdb.set_trace()
    return r, x

foo()    
```

I can run the above, enter the debugger, and manually edit x: `x = 44` and then `cont`, and it prints out `42 44`. But if I do the same, `r = 44`, it does not update.

**Comment by gotcha** [comment]
`r` is a `pdb`/`ipdb` command. To access your variable, you need to escape with `!`.

see https://docs.python.org/3/library/pdb.html#pdbcommand-!

It would be the same for all one letter commands
