### ISSUE TITLE
Exceptions caught incorrectly in `get_context_from_config`

### ISSUE THREAD

**Issue by bignose-debian** [gotcha/ipdb#234]
The exception handling in `get_context_from_config` makes incorrect assumptions, and catches exceptions that it does not handle correctly.

[In `get_context_from_config`](https://github.com/gotcha/ipdb/blob/04c99ff21a8ad1096c7340cf290d9c2baedb5e81/ipdb/__main__.py#L82), the statements

```python
parser = get_config()
return parser.getint("ipdb", "context")
```

are wrapped in a `try` block. But the `except` clauses evidently anticipate exceptions from the second statement only: they expect that the `parser` object exists and it was the `parser.getint` call that raised an exception.

This assumption is incorrect.

When the call to `get_config` raises a `ValueError`, it is erroneously caught as though raised from an already existing `parser`. Then the `except` clause attempts to use that object and it fails during exception handling.

> File "[…]/ipdb/__main__.py", line 89, in get_context_from_config
>     value = parser.get("ipdb", "context")
> UnboundLocalError: local variable 'parser' referenced before assignment

**Comment by bignose-debian** [comment]
An easy way to have the `get_config` call fail, is to have a badly-formatted `pyproject.toml` file. If that raises a `ValueError` it will be erroneously caught in the `get_context_from_config` logic as described above.

**Comment by bignose-debian** [comment]
I have implemented a test case which demonstrates this, and a simple change to correct it. See the branch [refine-exception-handling](https://git.sr.ht/~bignose/gotcha-ipdb/tree/wip/issue/234/refine-exception-handling) in my personal fork.

The test case (after refactoring to allow adding this test case) is:

```
    def test_noenv_nodef_invalid_setup(self):
        """
        Setup: $IPDB_CONFIG unset, $HOME/.ipdb does not exist,
            setup.cfg does not exist, pyproject.toml content is invalid.
        Result: Propagate exception from `get_config`.
        """
        os.unlink(self.env_filename)
        os.unlink(self.default_filename)
        os.unlink(self.setup_filename)
        write_lines_to_file(
            self.pyproject_filename,
            [
                "[ipdb]",
                "spam = abc",
            ],
        )
        with ModifiedEnvironment(IPDB_CONFIG=None, HOME=self.tmpd):
            try:
                cfg = get_context_from_config()
            except ValueError as exc:
                pass
            else:
                self.fail("Expected ValueError")
```

**Comment by gotcha** [comment]
Thanks for the analysis and the test !

Any reason this is not a PR ?

**Comment by bignose-debian** [comment]
On 09-Sep-2021, Godefroid Chapelle wrote:
> Thanks for the analysis and the test !

You're welcome, I hope it helps.

> Any reason this is not a PR ?

While Git is entirely distributed and allows us to collaborate, the
GitHub proprietary PR system doesn't work for repositories hosted
outside GitHub.

-- 
 \     “The Things to do are: the things that need doing, that you see |
  `\     need to be done, and that no one else seems to see need to be |
_o__)                   done.” —Richard Buckminster Fuller, 1970-02-16 |
Ben Finney ***@***.***>

**Comment by gotcha** [comment]
@bignose-debian I am fine adding your repo as remote to merge your changes myself.
Can you point me to the proper https git url  ?

**Comment by bignose-debian** [comment]
> @bignose-debian I am fine adding your repo as remote to merge your changes myself.
> Can you point me to the proper https git url ?

Yes, see the [summary page for that repository](https://git.sr.ht/~bignose/gotcha-ipdb).

**Comment by gotcha** [comment]
Your work has been included in master. See 333605e54db1eb224019eb378bb34bb72dc5d950.

Thanks a lot !

**Comment by gotcha** [comment]
Released in https://pypi.org/project/ipdb/0.13.11/
