### ISSUE TITLE
Will adding  `-m ipdb`  when running  Python affect the performance of the program?

### ISSUE THREAD

**Issue by you-n-g** [gotcha/ipdb#235]
Hi, 

Will adding  `-m ipdb`  when running  Python affect the performance of the program?

For example,
Will `python -m ipdb a.py` be slower than `python a.py` if `ipdb` debugger is not triggered? 

Thanks

**Comment by gotcha** [comment]
I do not fully know the answer:

1) I do think that Python will import ipdb and dependencies so startup will be slower.
2) I do not think it slows the rest of the execution but am not fully sure.
