### ISSUE TITLE
Heads up , adding ~/.pdbhistory to IPython and support for __decoratorskip__

### ISSUE THREAD

**Issue by Carreau** [gotcha/ipdb#236]
See https://github.com/ipython/ipython/pull/13157, 

let me know if that's ok, or if you have any concern about naming or location.

Also it will gain options to skip more frames:

https://github.com/ipython/ipython/pull/13142

Same questions about naming.

Thanks !

**Comment by MrMino** [comment]
I think you meant  `__debuggerskip__`?

**Comment by Carreau** [comment]
Oh yeah sorry.

**Comment by MrMino** [comment]
This can now be closed.

**Comment by zuxfoucault** [comment]
> See [ipython/ipython#13157](https://github.com/ipython/ipython/pull/13157),
> 
> let me know if that's ok, or if you have any concern about naming or location.
> 
> Also it will gain options to skip more frames:
> 
> [ipython/ipython#13142](https://github.com/ipython/ipython/pull/13142)
> 
> Same questions about naming.
> 
> Thanks !

Hi @Carreau I am trying to modify the path `~/.pdbhistory` to another path by
```
c = get_config()
c.TerminalInteractiveShell.debugger_history_file='/newplace/.pdbhistory'
```
in IPYTHONDIR/ipython_config.py

but it doesn't work. Do you have any suggestions how to modify the path? Thanks!

**Comment by Carreau** [comment]
You may want to open an issue in IPython repo, and if I have time i'll investigate. Otherwise as a comment on a closed issue I'll forget.

**Comment by zuxfoucault** [comment]
Sure! Thanks for the reminder!
