### ISSUE TITLE
ipdb `with launch_ipdb_on_exception():` gives pylint E1129 error mesage

### ISSUE THREAD

**Issue by avatar-lavventura** [gotcha/ipdb#246]
I am using: `ipdb==0.13.9`

------

For the code-block from answer for [Launch an IPython shell on exception](https://stackoverflow.com/a/37785862/2402577)

```python 
from ipdb import launch_ipdb_on_exception

with launch_ipdb_on_exception():
    main()
```

I am getting following warning message: 
`[not-context-manager] Context manager 'generator' doesn't implement __enter__ and __exit__. [E1129]`

How could I prevent this warning message?

**Comment by gotcha** [comment]
Which versions of Python and IPython ?

**Comment by avatar-lavventura** [comment]
```Python 3.8.10```. I am not using `IPython `.

**Comment by gotcha** [comment]
Well, if you use `ipdb`, you use `IPython` because it is a dependency. Can you check which version has been installed ?

**Comment by gotcha** [comment]
I do not see that warning when running with Python 3.8.8 and IPython 8.0.1.

**Comment by gotcha** [comment]
Could it be related to `pylint` ?

see https://github.com/PyCQA/pylint/issues/782

**Comment by avatar-lavventura** [comment]
````
ipdb==0.13.9
pylint==2.12.2
```

`pip freeze | grep IPython` returns empty.

**Comment by gotcha** [comment]
how did you install `ipdb` ? Are you in conda or jupyter or another environment ?

**Comment by avatar-lavventura** [comment]
The way I install `pip install ipdb -U`.

I am using just pure python, I am not using conda or jupyter or anything else.

I have `os.environ["PYTHONBREAKPOINT"] = "0"` in my python code and I just add ` breakpoint()  # DEBUG` into my code.

**Comment by gotcha** [comment]
When you install `ipdb` with `pip` like you describe above, it also installs `IPython`.
Do you know how to check which version got installed ?

Do you use `virtualenv` or `venv` or bare python ?

**Comment by gotcha** [comment]
Sorry for the delayed answer. I missed your post.

Did you try with a more recent IPython ?

`pip install ipython==8.7.0` in your `venv`

**Comment by gotcha** [comment]
@avatar-lavventura Just for my information, did this actually solve your issue ?

Or you are being polite when I answered so late and you did not have a need for a solve anymore ?

**Comment by avatar-lavventura** [comment]
I was polite as well :) But when I asked the question I believe latest version for `ipython` was `7.27.0`.  When I updated the ipython version, it is solved my issue.
