### ISSUE TITLE
Code reformatting in breakpoint REPL

### ISSUE THREAD

**Issue by mafrosis** [gotcha/ipdb#247]
Hello, as a many year `ipdb` user, the recent behaviour (I think) introduced in `ipython` 8 is driving me crazy 😄 

Now when I type:
```
ipdb> df['ts']
```

The output is:
```
ipdb> df["ts"]
0      2022-02-20 04:07:23
1      2022-02-19 11:22:22
2      2022-02-19 05:29:47
... snip
```

Note the conversion of apostrophe to quotation mark.

Worse, is this example. When I type:
```
ipdb> df.groupby([df.ts.dt.year, df.ts.dt.month, df.requester]).ts.count().nlargest(20)
```

The output is:
```
ipdb> df.groupby(
    [df.created_ts.dt.year, df.created_ts.dt.month, df.requester]
).created_ts.count().nlargest(20)
created_ts  created_ts  requester
2021        8           user1          19
                        user2          14
```

I've ignored it for a month or so, because when I'm in `ipdb` trying to fix something. I don't want quotation marks and newlines inserted automatically - it really disrupts my flow when I'm debugging. So much that I finally table flipped and went off to try to find out why... Google searches failed me.

Please tell me there's a config option somewhere which will disable this feature? Thanks for the great software! I ❤️ `ipdb`

**Comment by gotcha** [comment]
Quickly going through https://github.com/ipython/ipython/issues/13463 did not hint me that there is an easy way to disable that feature.

https://github.com/ipython/ipython/issues/13463#issuecomment-1014449047 seems to indicate that you will need to wait for next 8.1 release.
