### ISSUE TITLE
ipdb throws error when using a MultiIndex in pandas and python 3.10

### ISSUE THREAD

**Issue by ba-tno** [gotcha/ipdb#250]
I've stumbled upon an issue while using Spyder with pandas and python 3.10. Whenever the ipdb debugger hits a line where a MultiIndex is set, the following error is thrown:

```
AttributeError: 'MultiIndex' object has no attribute 'offsets'
```

This issue was already encountered by someone else, they reported it at pandas: https://github.com/pandas-dev/pandas/issues/46890
As the issue only occurred in Spyder I opened an issue there: https://github.com/spyder-ide/spyder/issues/17821
It was closed in favour of the pandas issue.

In the pandas issue a [commenter reproduced the error](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1124758743) and showed that this only happens with `ipdb` and not `pdb` or regular python.

As this issue is seemingly only occurring with the combination `ipdb` + `pandas` + `python=3.10` I am opening an issue here.

In case a conda environment is needed to reproduce the issue, you can check [this comment](https://github.com/spyder-ide/spyder/issues/17821#issuecomment-1117622458).

**Comment by gotcha** [comment]
[This comment](https://github.com/spyder-ide/spyder/issues/17821#issuecomment-1117655087) makes me think that the issue should be reported to ``IPython``.

(Reminder: ``ipdb`` is a lightweight wrapper around ``IPython``.)

PS: feel free to reopen if I am wrong.

**Comment by ba-tno** [comment]
Running the commands [from the example](https://github.com/spyder-ide/spyder/issues/17821#issue-1225260478) in `IPython` works fine:

![image](https://user-images.githubusercontent.com/52008464/168067450-3558850c-27dd-4a04-95ba-33b250099c66.png)

It's only when `ipdb` is imported that things break as shown in [this comment](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1124758743).

**Comment by FTL-Citepa** [comment]
I don't get it ,what I have to install ? what I have to uninstall, the example only shows what to do to reproduce the error

**Comment by ba-tno** [comment]
> the example only shows what to do to reproduce the error

That's the intention of the example: to show that it *does* work in `IPython` but it *does not* work in `ipdb`.

> I don't get it ,what I have to install ? what I have to uninstall,

You have to uninstall python 3.10 and install python 3.9 (or lower) in your environment.

**Comment by gotcha** [comment]
@ba-tno Why are you saying that it works with IPython when this screenshot also shows the `AttributeError` ?

https://user-images.githubusercontent.com/16781833/166795129-2bc7d34d-c0e6-401c-a458-77cf6ea96dfa.png

**Comment by gotcha** [comment]
I tried to reproduce your issue under Python 3.10.4 on my MacOS machine.

I did not get any error.

FTR, those are the versions of the packages I installed with:
`pip install pandas ipdb`

```
Package           Version
----------------- -------
appnope           0.1.3
asttokens         2.0.5
backcall          0.2.0
decorator         5.1.1
executing         0.8.3
ipdb              0.13.9
ipython           8.3.0
jedi              0.18.1
matplotlib-inline 0.1.3
numpy             1.22.3
pandas            1.4.2
parso             0.8.3
pexpect           4.8.0
pickleshare       0.7.5
pip               22.0.3
prompt-toolkit    3.0.29
ptyprocess        0.7.0
pure-eval         0.2.2
Pygments          2.12.0
python-dateutil   2.8.2
pytz              2022.1
setuptools        60.9.3
six               1.16.0
stack-data        0.2.0
toml              0.10.2
traitlets         5.2.0
wcwidth           0.2.5
wheel             0.37.1
```

**Comment by ba-tno** [comment]
> Why are you saying that it works with IPython when this screenshot also shows the `AttributeError` ?

Maybe I misunderstand what `ipdb` and `IPython` are, but as shown in [this comment](https://github.com/gotcha/ipdb/issues/250#issuecomment-1124895310) running the example in `IPython` (without importing `ipdb`) works fine.

Only when `ipdb` is imported and used, the error occurs as shown in [this comment](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1124758743) and in the screenshot you linked to (note the `ipbd>` in the prompt).

-------

## Reproduction environments
I have set-up two `conda` environments. In one I installed all packages using `conda`, in the other using `pip`. Both show the error when using `ipdb`.  In both I also installed [`spyder-kernels`](https://pypi.org/project/spyder-kernels/) as it is required to use the Spyder IDE with that environment.

These are the steps I followed:

1. Create two empty conda environments:
    ```
    conda create --name test-ipdb-conda --no-default-packages
    conda create --name test-ipdb-pip --no-default-packages
    ```
2. I set-up the `conda` environment with: `mamba install pandas=1.4.2 spyder-kernels=2.3 python=3.10.4 ipdb=0.13.9 -y`. I use [`mamba`](https://github.com/mamba-org/mamba) as it resolves faster than `conda`, but the resulting environment is the same:

    <details>
    <summary>Click to foldout environment.yml</summary>

    ```
    name: test-ipdb-conda
    channels:
      - conda-forge
    dependencies:
      - backcall=0.2.0=pyh9f0ad1d_0
      - backports=1.0=py_2
      - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
      - bzip2=1.0.8=h8ffe710_4
      - ca-certificates=2021.10.8=h5b45459_0
      - cloudpickle=2.0.0=pyhd8ed1ab_0
      - colorama=0.4.4=pyh9f0ad1d_0
      - debugpy=1.6.0=py310h8a704f9_0
      - decorator=5.1.1=pyhd8ed1ab_0
      - entrypoints=0.4=pyhd8ed1ab_0
      - intel-openmp=2022.0.0=h57928b3_3663
      - ipdb=0.13.9=pyhd8ed1ab_0
      - ipykernel=6.13.0=py310hbbfc1a7_0
      - ipython=7.33.0=py310h5588dad_0
      - jedi=0.18.1=py310h5588dad_1
      - jupyter_client=7.3.1=pyhd8ed1ab_0
      - jupyter_core=4.10.0=py310h5588dad_0
      - libblas=3.9.0=14_win64_mkl
      - libcblas=3.9.0=14_win64_mkl
      - libffi=3.4.2=h8ffe710_5
      - liblapack=3.9.0=14_win64_mkl
      - libsodium=1.0.18=h8d14728_1
      - libzlib=1.2.11=h8ffe710_1014
      - matplotlib-inline=0.1.3=pyhd8ed1ab_0
      - mkl=2022.0.0=h0e2418a_796
      - nest-asyncio=1.5.5=pyhd8ed1ab_0
      - numpy=1.22.3=py310hed7ac4c_2
      - openssl=3.0.3=h8ffe710_0
      - packaging=21.3=pyhd8ed1ab_0
      - pandas=1.4.2=py310hf5e1058_1
      - parso=0.8.3=pyhd8ed1ab_0
      - pickleshare=0.7.5=py_1003
      - pip=22.1=pyhd8ed1ab_0
      - prompt-toolkit=3.0.29=pyha770c72_0
      - psutil=5.9.0=py310he2412df_1
      - pygments=2.12.0=pyhd8ed1ab_0
      - pyparsing=3.0.9=pyhd8ed1ab_0
      - python=3.10.4=hcf16a7b_0_cpython
      - python-dateutil=2.8.2=pyhd8ed1ab_0
      - python_abi=3.10=2_cp310
      - pytz=2022.1=pyhd8ed1ab_0
      - pywin32=303=py310he2412df_0
      - pyzmq=22.3.0=py310h73ada01_2
      - setuptools=62.2.0=py310h5588dad_0
      - six=1.16.0=pyh6c4a22f_0
      - spyder-kernels=2.3.0=py310h5588dad_0
      - sqlite=3.38.5=h8ffe710_0
      - tbb=2021.5.0=h2d74725_1
      - tk=8.6.12=h8ffe710_0
      - tornado=6.1=py310he2412df_3
      - traitlets=5.2.0=pyhd8ed1ab_0
      - tzdata=2022a=h191b570_0
      - ucrt=10.0.20348.0=h57928b3_0
      - vc=14.2=hb210afc_6
      - vs2015_runtime=14.29.30037=h902a5da_6
      - wcwidth=0.2.5=pyh9f0ad1d_2
      - wheel=0.37.1=pyhd8ed1ab_0
      - xz=5.2.5=h62dcd97_1
      - zeromq=4.3.4=h0e60522_1
    prefix: C:\Users\user\Miniconda3\envs\test-ipdb-conda
    ```

    </details>

3. Then I go to the `pip` environment (`conda deactivate; conda activate test-ipdb-pip`) and install all packages with `pip` using: `pip install pandas==1.4.2 spyder-kernels==2.3.0 ipdb==0.13.9`. The output of `pip freeze` is:

    <details>
    <summary>Click to foldout reqruirements.txt</summary>

    ```
    backcall==0.2.0
    cloudpickle==2.0.0
    colorama==0.4.4
    debugpy==1.6.0
    decorator==5.1.1
    entrypoints==0.4
    ipdb==0.13.9
    ipykernel==6.13.0
    ipython==7.33.0
    jedi==0.18.1
    jupyter-client==7.3.1
    jupyter-core==4.10.0
    matplotlib-inline==0.1.3
    nest-asyncio==1.5.5
    numpy==1.22.3
    packaging==21.3
    pandas==1.4.2
    parso==0.8.3
    pickleshare==0.7.5
    prompt-toolkit==3.0.29
    psutil==5.9.0
    Pygments==2.12.0
    pyparsing==3.0.9
    python-dateutil==2.8.2
    pytz==2022.1
    pywin32==304
    pyzmq==22.3.0
    six==1.16.0
    spyder-kernels==2.3.0
    toml==0.10.2
    tornado==6.1
    traitlets==5.2.0
    wcwidth==0.2.5
    ```

    </details>

4. I create the following test file as `test-ipdb.py`:
    ```
    import pandas as pd

    df = pd.DataFrame({"a": [1, 2, 3], "b": [100, 200, 300], "c": ["a", "b", "c"]})

    df.set_index("a", inplace=True)
    import ipdb; ipdb.set_trace()
    df.set_index("b", append=True, inplace=True)

    print(df)
    print(df.index)
    ```
5. I run the file in each environment:
    
    ```
    PS C:\Users\user> conda activate test-ipdb-conda; python .\t.py
    > c:\users\user\t.py(7)<module>()
          6 import ipdb; ipdb.set_trace()
    ----> 7 df.set_index("b", append=True, inplace=True)
          8

    ipdb> n
    AttributeError: 'MultiIndex' object has no attribute 'offsets'
    > c:\users\user\t.py(7)<module>()
          6 import ipdb; ipdb.set_trace()
    ----> 7 df.set_index("b", append=True, inplace=True)
          8

    ipdb>
    ```

    ```
    PS C:\Users\user> conda activate test-ipdb-pip; python .\t.py
    > c:\users\user\t.py(7)<module>()
          6 import ipdb; ipdb.set_trace()
    ----> 7 df.set_index("b", append=True, inplace=True)
          8

    ipdb> n
    AttributeError: 'MultiIndex' object has no attribute 'offsets'
    > c:\users\user\t.py(7)<module>()
          6 import ipdb; ipdb.set_trace()
    ----> 7 df.set_index("b", append=True, inplace=True)
          8

    ipdb>
    ```

As can be seen, the result is the same regardless of `conda` or `pip`: setting a MultiIndex throws an `AttributeError`.

**Comment by ba-tno** [comment]
I noticed that because of `spyder-kernels=2.3.0` an older version of `IPython` was being installed (`7.33.0`). I went ahead and updated `IPython` with below command. I had to accept that `spyder-kernels` would then be downgraded.

```
conda activate test-ipdb-conda
mamba install ipython=8.3.0 -y
```

Then I ran the test code again, unfortunately with the same error.

**Comment by gotcha** [comment]
Disclaimer: I am no `conda` user,  even less expert.

Nevertheless, I did try to reproduce your setup and still did not manage to get to the issue.

I installed `conda` with `brew`.

Then created an environment with:
```
/usr/local/anaconda3/bin/conda create -c conda-forge --name ippan ipdb pandas spyder-kernels
```

If I run `bin/pip list` in that environment, this is what I get:
```
Package                       Version
----------------------------- -------
appnope                       0.1.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
cloudpickle                   2.0.0
debugpy                       1.6.0
decorator                     5.1.1
entrypoints                   0.4
ipdb                          0.13.9
ipykernel                     6.13.0
ipython                       7.33.0
jedi                          0.18.1
jupyter-client                7.3.1
jupyter-core                  4.10.0
matplotlib-inline             0.1.3
nest-asyncio                  1.5.5
numpy                         1.22.3
packaging                     21.3
pandas                        1.4.2
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.1
prompt-toolkit                3.0.29
psutil                        5.9.0
ptyprocess                    0.7.0
Pygments                      2.12.0
pyparsing                     3.0.9
python-dateutil               2.8.2
pytz                          2022.1
pyzmq                         22.3.0
setuptools                    62.2.0
six                           1.16.0
spyder-kernels                2.3.0
tornado                       6.1
traitlets                     5.2.0
wcwidth                       0.2.5
wheel                         0.37.1
wurlitzer                     3.0.2
```

My wild guess is that you have some sort of global configuration/package installed that is polluting your environment. I am afraid it will be hard for me to help deeper with your specific setup.

Feel free to ask questions though, I'll make my best to answer.

**Comment by FTL-Citepa** [comment]
> Disclaimer: I am no `conda` user, even less expert.
> 
> Nevertheless, I did try to reproduce your setup and still did not manage to get to the issue.
> 
> I installed `conda` with `brew`.
> 
> Then created an environment with:
> 
> ```
> /usr/local/anaconda3/bin/conda create -c conda-forge --name ippan ipdb pandas spyder-kernels
> ```
> 
> If I run `bin/pip list` in that environment, this is what I get:
> 
> ```
> Package                       Version
> ----------------------------- -------
> appnope                       0.1.3
> backcall                      0.2.0
> backports.functools-lru-cache 1.6.4
> cloudpickle                   2.0.0
> debugpy                       1.6.0
> decorator                     5.1.1
> entrypoints                   0.4
> ipdb                          0.13.9
> ipykernel                     6.13.0
> ipython                       7.33.0
> jedi                          0.18.1
> jupyter-client                7.3.1
> jupyter-core                  4.10.0
> matplotlib-inline             0.1.3
> nest-asyncio                  1.5.5
> numpy                         1.22.3
> packaging                     21.3
> pandas                        1.4.2
> parso                         0.8.3
> pexpect                       4.8.0
> pickleshare                   0.7.5
> pip                           22.1
> prompt-toolkit                3.0.29
> psutil                        5.9.0
> ptyprocess                    0.7.0
> Pygments                      2.12.0
> pyparsing                     3.0.9
> python-dateutil               2.8.2
> pytz                          2022.1
> pyzmq                         22.3.0
> setuptools                    62.2.0
> six                           1.16.0
> spyder-kernels                2.3.0
> tornado                       6.1
> traitlets                     5.2.0
> wcwidth                       0.2.5
> wheel                         0.37.1
> wurlitzer                     3.0.2
> ```
> 
> My wild guess is that you have some sort of global configuration/package installed that is polluting your environment. I am afraid it will be hard for me to help deeper with your specific setup.
> 
> Feel free to ask questions though, I'll make my best to answer.

Ok, for me it may be a global configuration messing with my environment, because I had packages conflicts (I'm new in the conda game and I was confused with conda-forge and pip install) so I had to create a new environment to make my scripts work. So how could I "clean" a base environment that is polluting my environment?

**Comment by gotcha** [comment]
@FTL-Citepa I suggest you ask that question in the `conda` community. As said above I am not a user even less an expert.

The only thing I think I understand is that `conda` environments look (are ?) like `virtualenv`(`venv` ?). They could interact in unforeseen ways with your system (global ?) python. But because I guess, this could be totally wrong.

If you really need an answer here, transmit your various bug reports to helpful people in the `conda`community.

Good luck.

**Comment by ba-tno** [comment]
[This issue is resolved](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1208455954) in pandas 1.4.3 and/or Spyder 5.3.2, hence closing.

**Comment by gotcha** [comment]
@ba-tno Thanks for follow up.
