### ISSUE TITLE
SetupTools has dropped 2to3 support

### ISSUE THREAD

**Issue by bobtwinkles** [gotcha/ipdb#251]
This results in install failures unless SetupTools is pinned to versions < 58 (https://setuptools.pypa.io/en/latest/history.html#id294).

It may be time to move on from Python 2, it's been completely unsupported for several years now.

**Comment by gotcha** [comment]
`2to3` usage was ditched since `ipdb==0.12.3` afaik.

See https://github.com/gotcha/ipdb/commit/01e96f845c2bb15947374236788b68f66c99b8b6

Which version are you using ?

**Comment by bobtwinkles** [comment]
I thought I was using the latest 0.12, but apparently not. I will debug my environment to determine what went wrong. I think #243 can also be closed then =).
