### ISSUE TITLE
Migrate from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by mbrukman** [gotcha/ipdb#253]
Looking at https://travis-ci.org/github/gotcha/ipdb, we see the banner from Travis CI:

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

and also, the last build ran "about a year ago" which matches the timing of when travis-ci.org stopped working.

I saw in https://github.com/gotcha/ipdb/pull/208#issuecomment-788830883 that there's a plan to move from Travis CI to GitHub Actions, but looks like the move hasn't happened yet.

If you're interested, you can use a [GitHub template for Python project testing](https://github.com/gotcha/ipdb/new/master?filename=.github%2Fworkflows%2Fpython-package.yml&workflow_template=python-package) or take a look at [my simple config](https://github.com/mbrukman/csv2txf/blob/main/.github/workflows/main.yml) as a starting point and add the additional Python versions and test / coverage commands you have in your [`.travis.yml`](https://github.com/gotcha/ipdb/blob/3f41e83816e7c0c31a9e25b7ceec2f8980c5bd8a/.travis.yml). Let me know if you have questions or need help with this.

Note that you'll have to first [enable GitHub Actions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository) for this repository before starting to use it.

**Comment by gotcha** [comment]
PR welcome ;-)

**Comment by gotcha** [comment]
Done in ed364d4c190058196f3a66600f3970f44b0ef55b
