### ISSUE TITLE
Remove toml dependency for Python 3.11+

### ISSUE THREAD

**Issue by salty-horse** [gotcha/ipdb#259]
Python 3.11 comes bundled with [tomllib](https://docs.python.org/3/library/tomllib.html), which allows reading toml files, and has the same interface as the toml library.

For compatible versions, there dependency on toml can be removed.

**Comment by gotcha** [comment]
PR welcome ;-)

**Comment by salty-horse** [comment]
I would, but I'm not familiar with how to specify the versions in `setup.py`, nor how to test the packaging file. Is it like so?

```
':python_version > "3.6" and python_version < "3.11"': ['ipython >= 7.17.0', 'toml >= 0.10.2', 'decorator'],
':python_version >= "3.11"': ['ipython >= 7.17.0', 'decorator'],
```

**Comment by gotcha** [comment]
Released in https://pypi.org/project/ipdb/0.13.10/
