### ISSUE TITLE
Connect to an existing kernel

### ISSUE THREAD

**Issue by fecet** [gotcha/ipdb#267]
Possible to attach ipdb to an existing kernel? 

Currently, ipdb starts a new kernel session each time it is called, which can be inconvenient and time-consuming. If ipdb could connect to an existing kernel session, it would be much more efficient for debugging.

I believe this feature would be useful for many developers who use ipdb in conjunction with Jupyter notebooks or other interactive environments.

**Comment by gotcha** [comment]
`ipdb` is a community project. PR welcome !

**Comment by fecet** [comment]
I found a workaround is to use `jupyter console` to connect and use ipdb in it, but the ipdb in jupyter console seems buggy and fallback to a "naive" terminal, arrow key and tab not work as in ipython per https://github.com/jupyter/jupyter_console/issues/162. Why this happen?

**Comment by gotcha** [comment]
I am not a regular Jupyter user so I am afraid I cannot really help.

Nevertheless, can you detail what you mean by using ipdb in jupyter ?

**Comment by fecet** [comment]
Enter jupyter console, trigger an error like `1/0`, then use `%debug` enter it:
![image](https://user-images.githubusercontent.com/41792945/231991457-6f85b7e3-13eb-41e4-b158-9295e8668e46.png)
You can see the name of `ipdb` is white, arrow keys will result escape sequences and tab will print a whitespace and wouldn't trigger completion.
If we enter ipython and do the same things, we get
![image](https://user-images.githubusercontent.com/41792945/231991968-1bc2aacd-e3bc-43da-8304-796b3f820a31.png)
where the `ipdb` is green, indicate it's work like in ipython, and it did, we can use arrow keys to navigate history and trigger completion by tab in it.

**Comment by gotcha** [comment]
`jupyter-console` does not depend on `ipdb` as shown here: https://github.com/jupyter/jupyter_console/blob/main/pyproject.toml

I guess that the `ipdb` prompt displayed in `jupyter-console` is the `IPython` debugger.
IOW, issues with the `ipdb` in `jupyter-console`should be reported to the maintainers of that package.

(Similarly, `ipdb` is a wrapper around the given debugger.)

**Comment by gotcha** [comment]
> Possible to attach ipdb to an existing kernel?
> 
> Currently, ipdb starts a new kernel session each time it is called, which can be inconvenient and time-consuming. If ipdb could connect to an existing kernel session, it would be much more efficient for debugging.

The same way, I guess that the `ipdb` you refer here is not this package.
Did you install the `ipdb` package in any way ?

**Comment by fecet** [comment]
You are correct. According to the information found at https://github.com/jupyter/qtconsole/issues/143 and https://github.com/jupyter/qtconsole/issues/99, it appears that this is an open problem. Thank you for sharing your insight, and I apologize for opening this here
