### ISSUE TITLE
Feature request: Add a way to continue to a specific breakpoint

### ISSUE THREAD

**Issue by oren0e** [gotcha/ipdb#271]
If I have a code that contains multiple breakpoints, I want the option to be able to continue to a specific one, e.g:
```python
breakpoint()
print("hello")
result = do_something()
breakpoint()
print("foo")
breakpoint()
close()
```
So if I start debugging with ipdb I want to be able to do something like
```
ipdb> c 6
```
to continue straight to the breakpoint on line 6.
Is this possible to do?

**Comment by gotcha** [comment]
`ipdb` is a light wrapper around IPython debugger which itself derives from `pdb` of Python standard library.

In other words, adding commands should be suggested at those levels.

In the meanwhile, https://docs.python.org/3/library/pdb.html might be a good read.
