### ISSUE TITLE
What is `sset_trace`?

### ISSUE THREAD

**Issue by galenseilis** [gotcha/ipdb#286]
On the README I see this example:

```python
import ipdb
ipdb.sset_trace()
ipdb.spm()

from ipdb import slaunch_ipdb_on_exception
with slaunch_ipdb_on_exception():
    ...
```

At first I thought that `sset_trace`, but when I ran it in an interactive Python session I found that it appeared to start a trace... but I am not clear about why that worked or why it exists as an alternative to `set_trace`. 

What is `sset_trace`? How does it differ from `set_trace`?

**Comment by disconnect3d** [comment]
It is documented here - https://pypi.org/project/ipdb/:
<img width="785" alt="image" src="https://github.com/user-attachments/assets/4ada1ec1-b342-409c-8f53-815dc7f40b68">

You can also check the code yourself: https://github.com/gotcha/ipdb/blob/400e37c56c9772fdc4c04ddb29d8a4a20568fb1a/ipdb/stdout.py#L9-L18 ;)

**Comment by galenseilis** [comment]
@disconnect3d Thanks!

(Also, nice Warcraft III profile picture. I recall getting Warcraft III when it first came out. Fond memories of playing it.)
