### ISSUE TITLE
Allow configuration of ipdb context

### ISSUE THREAD

**Issue by jarradsl** [gotcha/ipdb#35]
In order to greatly improve usability, the debugger should be able to be configured to display more lines of context. The current default of 3 lines makes it difficult to know where you are in the code.

A 'fullscreen' option that fills the terminal window would be nice as well and would behave a lot more like a visual debuggers.

**Comment by JamshedVesuna** [comment]
@gotcha currently working on that with [ipython/ipython#9087](https://github.com/ipython/ipython/issues/9087#issuecomment-166428841). Following down the stack:

1. ipdb makes a [call to Pdb's set_trace](https://github.com/gotcha/ipdb/blob/master/ipdb/__main__.py#L135)
2. [Pdb](https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L201) inherits the unbound set_trace method from [pdb](https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L60)
3. [pdb.set_trace()](https://hg.python.org/cpython/file/2.7/Lib/pdb.py#l1250) [inherits bdb](https://hg.python.org/cpython/file/2.7/Lib/pdb.py#l59)
4. Finally, the call to [bdb.set_trace()](https://hg.python.org/cpython/file/2.7/Lib/bdb.py#l212) is made

One option is to edit `bdb.set_trace()` / [`pdb.print_stack_entrty`](https://hg.python.org/cpython/file/2.7/Lib/pdb.py#l893). Alternatively, we can edit IPython. Either way, I think a simple change to ipdb would be to add a keyword to [set_trace](https://github.com/gotcha/ipdb/blob/master/ipdb/__main__.py#L135) (such as `context=3`) if the method allows it.

**Comment by JamshedVesuna** [comment]
With [ipython/ipython PR 9097](https://github.com/ipython/ipython/pull/9097), a simple change to ipdb would be to add the keyword arg `context` to [`set_trace`](https://github.com/gotcha/ipdb/blob/master/ipdb/__main__.py#L130). Then, see if `Pdb` accepts the keyword arg `context` (for backwards compatibility), and if so, pass it through. I'd be happy to make a PR as soon as [ipython/ipython PR 9097](https://github.com/ipython/ipython/pull/9097) is merged.

**Comment by gotcha** [comment]
Good :-)

**Comment by JamshedVesuna** [comment]
Added PR #75, waiting for [ipython/ipython #9097](https://github.com/ipython/ipython/pull/9097) to be merged.

**Comment by JamshedVesuna** [comment]
Update: [ipython #9097](https://github.com/ipython/ipython/pull/9097) has been merged! Support for the `context` keyword arg is now supported!

**Comment by JamshedVesuna** [comment]
Is it worth waiting until ipython 4.1 is released before this is merged?

**Comment by FrancescElies** [comment]
It would be lovely to see this one merged

**Comment by JamshedVesuna** [comment]
Excited to use this feature! When will it be included in 0.8.2?

**Comment by gotcha** [comment]
#75 has been released in 0.8.2
