### ISSUE TITLE
Importing ipdb in ipython startup files breaks tab completion.

### ISSUE THREAD

**Issue by mforbes** [gotcha/ipdb#63]
I don't know exactly why yet, but importing ``ipdb`` in IPython startup files (i.e. ``~/.ipython./profile_default/startup/``) breaks tab completion.

The issue has to do with line 32 in ``ipdb/__main__.py`` which tests for the global symbol ``get_ipython``.  At this early state of startup, the global symbol is not defined, and then something in the ``except NameError:`` block breaks the completer.  (Somehow the completer that can actually do completions is replaced with another broken completer.  Probably due to the embedding.)

Is there a more robust way of doing this test that will also work in the startup files?

**Comment by gotcha** [comment]
Can you give more details about the way you use ipdb in IPython startup files ?

**Comment by mforbes** [comment]
All I do is ``import ipdb``.  To be explicit, create a file ``.ipython/profile_default/startup/00-first.py`` with this import, then start ``ipython`` and try tab completing after something like ``import sys``.  ``sys.<tab>`` should list something like ``sys.api_version``, ``sys.argv``, etc. but this is broken if any of the startup files ``import ipdb`` (at least with the latest version installed by pip: ``ipdb-0.8.1``.)

**Comment by gotcha** [comment]
I feel this issue is not deep enough for me to work on it. Any PR accepted though.

**Comment by mforbes** [comment]
I don't understand the backwards compatibility issues that led to the current code, but why not just:

```
    def_colors = IPython.get_ipython().colors
```

instead of relying on the global `get_ipython.im_self.colors`?

**Comment by gotcha** [comment]
The latest versions does not have that code anymore.

Have you tried https://pypi.python.org/pypi/ipdb/0.8.3 ?

**Comment by mforbes** [comment]
Looks like this is resolved (I am trying now with 0.9.0.  btw, it would be nice to define `ipdb.__version__` or something similar.  I could not find out how to programatically determine the version.)
