### ISSUE TITLE
AttributeError with old ipython

### ISSUE THREAD

**Issue by toobaz** [gotcha/ipdb#64]
I wouldn't open a bug triggered by an old checkout of iPython, but then I saw that the code integrates some efforts to support several of them, so...

I am using a git checkout of iPython from May (simply because I never installed a newer version of Tornado), and importing ipdb results in

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-2d6f026194dd> in <module>()
    ----> 1 import ipdb

    /home/nobackup/repo/ipdb/ipdb/__init__.py in <module>()
         14 # You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.>
         15 
    ---> 16 from ipdb.__main__ import set_trace, post_mortem, pm, run, runcall, runeval, launch_ipdb_on_exception
         17 
         18 pm                       # please pyflakes

    /home/nobackup/repo/ipdb/ipdb/__main__.py in <module>()
         52         def_colors = ipshell.colors
         53     else:
    ---> 54         def_colors = get_ipython.im_self.colors
         55 
         56     from IPython.utils import io

    AttributeError: 'function' object has no attribute 'im_self'

I ignore if this happens with some official release, but I'm submitting a fix.

**Comment by gotcha** [comment]
I guess this got solved by comparing versions properly.
