### ISSUE TITLE
How to access ipython command in ipdb

### ISSUE THREAD

**Issue by QiangF** [gotcha/ipdb#71]
Hi everyone,
When I execute a function in ipython, it stops at an error, I use the magic %debug, now I enter ipdb. 
How do I get ipython command like who and whos? Is there a hook for entering ipdb so I can define my own commands?
Thank you!

**Comment by gotcha** [comment]
This is a question you should ask to the IPython community.
ipdb package/egg is a wrapper around IPython debugger which displays itself as `ipdb`
