### ISSUE TITLE
Error when used with py.test

### ISSUE THREAD

**Issue by marco-santamaria** [gotcha/ipdb#78]
When I write 'import ipdb; ipdb.set_trace()' inside a py.test test launched with the '-k' option from the console I get the following error:

`[TerminalIPythonApp] CRITICAL | Unrecognized flag: '-k'`

This only happens with the last version (0.8.2) and not with previous one (0.8.1)

**Comment by gotcha** [comment]
Can you check if you still have the issue with 0.8.3 ?

**Comment by gotcha** [comment]
@marco-santamaria without opposition from you, I'll consider this as fixed.

**Comment by marco-santamaria** [comment]
No problem with 0.8.3 and 0.9.0! Thanks!

**Comment by gotcha** [comment]
Thanks for the report
