### ISSUE TITLE
Unexpected behavior.

### ISSUE THREAD

**Issue by Unknowny** [gotcha/ipdb#79]
Not sure how it happens but when I type `ipdb> foo.bar('123').baz()` then move the cursor to the start and enter any character it throws me to the second quote character and somehow messes up whole line.
Screencast: http://webmshare.com/Mn9jB

**Comment by gotcha** [comment]
Is that a bug seen only in 0.8.2 ?

**Comment by Unknowny** [comment]
Present in 0.5 too (can't test bellow - throws ipython debugger error).
P.S. Sometimes it happens when I remove the newly inserted character.

**Comment by Unknowny** [comment]
Another thing: http://webmshare.com/R5dnA
While browsing history part of code became part of the prompt.
Maybe something on my side, no way that I didn't encounter it before.

**Comment by gotcha** [comment]
Can you check if you can reproduce with IPython itself ? I have the gut feeling this is not related to ipdb integration code.

**Comment by Unknowny** [comment]
Yep, looks like an issue with IPython debugger working in colorized mode.

**Comment by gotcha** [comment]
I suggest you file the bug in IPython. I'll close this issue?
