### ISSUE TITLE
Errors importing ipdb

### ISSUE THREAD

**Issue by cchrysostomou** [gotcha/ipdb#81]
I cannot seem to be able to import ipdb when using ipython notebook. I can import ipdb in all other instances (i.e. ipython terminal or python terminal).

I am using jupyter 4.0.6 and ipython (4.1.1).

When I import ipdb using ipython/jupyter, I receive the following error:

`---------------------------------------------------------------------------
MultipleInstanceError                     Traceback (most recent call last)
<ipython-input-2-b424f80b510d> in <module>()
      1 import sys
      2 print(sys.version)
----> 3 import ipdb

/usr/local/lib/python3.4/dist-packages/ipdb/**init**.py in <module>()
     14 # You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
     15 
---> 16 from ipdb.**main** import set_trace, post_mortem, pm, run, runcall, runeval, launch_ipdb_on_exception
     17 
     18 pm                       # please pyflakes

/usr/local/lib/python3.4/dist-packages/ipdb/**main**.py in <module>()
     71         # the instance method will create a new one without loading the config.
     72         # i.e: if we are in an embed instance we do not want to load the config.
---> 73         ipapp = TerminalIPythonApp.instance()
     74         shell = get_ipython()
     75         def_colors = shell.colors

/usr/local/lib/python3.4/dist-packages/traitlets/config/configurable.py in instance(cls, _args, *_kwargs)
    413             raise MultipleInstanceError(
    414                 'Multiple incompatible subclass instances of '
--> 415                 '%s are being created.' % cls.**name**
    416             )
    417 

MultipleInstanceError: Multiple incompatible subclass instances of TerminalIPythonApp are being created.`

**Comment by gotcha** [comment]
which version of ipdb are you using ?

**Comment by costas821** [comment]
Version 0.9.

**Comment by gotcha** [comment]
Would you mind checking if you get the error with 0.8.1 ?

**Comment by costas821** [comment]
Version 0.8.1 does not raise an error

**Comment by michaelaye** [comment]
I have this error as well using ipdb 0.10.1

**Comment by bnaul** [comment]
This error is still present in `ipdb==0.10.2`; are there any plans to make `ipdb` compatible with new versions of `jupyter` and `ipython`? It seems `ipdb` hasn't worked with the latest versions of each for nearly a year.

**Comment by abdulqayyum** [comment]
Got same error in `ipdb: 0.10.2` so is there any proper workaround?

**Comment by bnaul** [comment]
@abdulqayyum I have moved away from `ipdb` in favor of the built-in debugger:
```
import IPython.core.debugger

IPython.core.debugger.set_trace()
```
Works great in either the notebook or the terminal, just not very well documented.

**Comment by laike9m** [comment]
This issue still has not been fixed, serious?

**Comment by MYounas** [comment]
Please @gotcha fixed the multiple instance error,I am using 0.10.3.

**Comment by takluyver** [comment]
I think #143 should fix this (it also removes support for IPython <5, but hopefully that's not a big issue for anyone).

**Comment by gotcha** [comment]
Released in https://pypi.python.org/pypi/ipdb/0.11
