### ISSUE TITLE
Home button spoils the command line

### ISSUE THREAD

**Issue by axil** [gotcha/ipdb#87]
Running a file consisting of the line

import ipdb;ipdb.set_trace()

then entering more than 19 or more arbitrary characters in the command line and then hitting Home button (or Ctrl-A) makes the cursor go to position 11 instead of position 0 of the line and the line is garbaged as a result (it doesn't let me to the left of the 11th position in the line):

$ python ~test/c.py 
--Return--
None
> /home/test/c.py(2)<module>()
      1 import ipdb
----> 2 ipdb.set_trace()

ipdb> 1234567890123456789
Now pressing Home and then '_':

ipdb> 12345678901_1234567890123456789
while I expected it to be

ipdb> _1234567890123456789
Fresh install of Ubuntu and fresh install of Archlinux, python 2.7.10, 3.4.3+ are both affected. No libs except for ipdb 0.7, 0.8 or 0.9 (+dependencies) are installed.

Everything is ok in ipython, python and pdb.set_trace command lines.

Tested in terminal, terminator and text terminal (ctrl-alt-f1), using bash and zsh.

Reproduced by another user:
http://stackoverflow.com/questions/35671018/home-button-bug-in-ipdb-on-ubuntu

**Comment by jclevesque** [comment]
I have experienced this on both Ubuntu and Archlinux as well. Doesn't matter which type of terminal it is (gnome-terminal, uxterm). Makes it rather hard to use ipdb.

**Comment by jclevesque** [comment]
It is also impossible to erase/modify those first 11 characters afterwards, in any way (left arrow won't go back either).

**Comment by gotcha** [comment]
@jclevesque Do you see this issue with `ipdb 0.7` as well ?

**Comment by jclevesque** [comment]
Yes, I setup a virtualenv with ipdb 0.7, and I still had the same issue.

It might be related to another package, as pip automatically fetched the following packages given my initial command (`pip install ipdb==0.7`):

`decorator-4.0.9 ipdb-0.7 ipython-4.1.2 ipython-genutils-0.1.0 path.py-8.1.2 pexpect-4.0.1 pickleshare-0.6 ptyprocess-0.5.1 simplegeneric-0.8.1 traitlets-4.1.0`

**Comment by jclevesque** [comment]
It works when using a different IPython version (2.0.0), with both ipdb 0.7 and 0.9. It seems to be related to the terminal colouring, as with IPython 2 I didn't get a coloured ipdb prompt.

Tested with IPython 3, which also does not have colouring, still not issue. It really seems to be related to IPython 4 and the coloured terminal.

**Comment by jclevesque** [comment]
Seems to be something that changed between IPython 4.0 and 4.1. For my part, I downgraded IPython to 4.0 and all my stuff still works so I am happy.

**Comment by gotcha** [comment]
@axil Can you confirm what @jclevesque sees ?

**Comment by axil** [comment]
@gotcha Yes, downgrading to IPython==4.0.0 fixes this issue. Theoretically we can git bisect IPython revisions to find the wrong line.

**Comment by gotcha** [comment]
@axil 

> Everything is ok in ipython, python and pdb.set_trace command lines.

Does that mean that the issue does not happen under IPython only ?

**Comment by axil** [comment]
>  Does that mean that the issue does not happen under IPython only ?
That's right

**Comment by jianli** [comment]
iPython introduced this bug in `4.1.0`. It's been fixed at https://github.com/ipython/ipython/issues/9243, but that fix is only available in `5.0.0.dev`.

See also #79
