### ISSUE TITLE
Add user defined context value to list

### ISSUE THREAD

**Issue by JamshedVesuna** [gotcha/ipdb#89]
By default, `list` displays 10 lines. It would be nice if users could pass in a larger `context` value.

**Comment by gotcha** [comment]
Have you tried the help command ? You can specify lines when using list.

**Comment by JamshedVesuna** [comment]
Right now, the user experience for `list` isn't that great. The second arg has two purposes:

Specifying the end range, or, if it is less than the first arg, specifies the context size. It would be great if the user defined context was a keyword argument. That way, the first two args specify the range, and the range only.

So the `list  signature would look like:
```python
def list(start_range, end_range, context=11):
    ...
```

@gotcha what do you think?

**Comment by gotcha** [comment]
As `ipdb` is just a light wrapper around `IPython` debugger, `ipdb` does not have control of IPython debugger UI.

You should make your suggestion to IPython team : https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L461
