### ISSUE TITLE
Error in argument for list of OrderedDict keys

### ISSUE THREAD

**Issue by max5555** [gotcha/ipdb#92]
```
ipdb> from collections import OrderedDict
ipdb> OrderedDict(((1,2),)).keys()
KeysView(OrderedDict([(1, 2)]))
ipdb> list(OrderedDict(((1,2),)).keys())
*** Error in argument: '(OrderedDict(((1,2),)).keys())'
```
## 

ipdb 0.9.0
IPython 2.3.0
Python 3.4.3

**Comment by gotcha** [comment]
Have you tried in IPython itself ?

**Comment by max5555** [comment]
Yes I tried: no errors:

> ➜  ~ ipython3
> Python 3.4.3 (default, Oct 14 2015, 20:33:09) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 2.3.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> In [1]: from collections import OrderedDict
> 
> In [2]: list(OrderedDict(((1,2),)).keys())
> Out[2]: [1]
>

**Comment by kreedz** [comment]
It's related to https://github.com/gotcha/ipdb/issues/106.

**Comment by gnebehay** [comment]
same solution as #106, use
```
!list
```

**Comment by gotcha** [comment]
@gnebehay Thanks for triaging !
