### ISSUE TITLE
Aliasing pdb = ipdb

### ISSUE THREAD

**Issue by miohtama** [gotcha/ipdb#98]
What methods there would be alias the standard library pdb module with ipdb, so that anything that triggers pdb would actually trigger ipdb? This include at least
- `import pdb ; pdb.set_trace()`
- `py.test --pdb`

If I am not incorrect pdbpp module does something to provide this kind of functionality https://pypi.python.org/pypi/pdbpp/

**Comment by gotcha** [comment]
I do not understand what you mean. Anyway PR welcome !

**Comment by gnebehay** [comment]
I guess the closest you can get to easily is
```
import ipdb as pdb;
pdb.set_trace()
```
