### ISSUE TITLE
MultipleInstanceError

### ISSUE THREAD

**Issue by rymnikski** [gotcha/ipdb#99]
MultipleInstanceError: Multiple incompatible subclass instances of TerminalIPythonApp are being created.

The version 0.10 seems to be incompatible with Ipython.

**Comment by gotcha** [comment]
Can you tell which IPython version you use ?
And give an example of what is going wrong ?

**Comment by rymnikski** [comment]
Hi.
IPython ==  4.1.2
the error occurs in the beginning when you import the library.
Other users seems to be the same problem.

http://stackoverflow.com/questions/35613249/using-ipdb-to-debug-python-code-in-one-cell-jupyter-or-ipython

My solution, for now, is downgrading: pip install ipdb == 0.8

**Comment by Liam3851** [comment]
Same issue-- for a little more clarity, as rymnikski's link indicates, this is an incompatibility with the Jupyter notebook. When opening a fresh Jupyter notebook with IPython 4.1.2+ (including 4.2), importing the ipdb module blows with MultipleInstanceError. ipdb works fine in the ipython terminal.

**Comment by gotcha** [comment]
IOW, `ipdb` logic to check for a running instance will need to be improved.

**Comment by gnebehay** [comment]
Duplicate of #81

**Comment by gotcha** [comment]
https://pypi.python.org/pypi/ipdb/0.11
